<?php
// for includes
define("DIR_ROOT", __DIR__."/");
define("DIR_CSS", DIR_ROOT."css/");
define("DIR_SRC", DIR_ROOT."src/");
define("DIR_WEB", DIR_ROOT."web/");
define("DIR_LOC", DIR_ROOT."local/");
define("DIR_TST", DIR_ROOT."test/");
define("DIR_ADM", DIR_ROOT."admin/");
define("DIR_IMG", DIR_ROOT."img/");

// for links
define("LINK_BASE", (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]");
define("LINK_SUBDIR", "/~jday/MSIS-2630/A-Recipe-Website");
define("LINK_ROOT", LINK_BASE.LINK_SUBDIR."/");
define("LINK_CSS", LINK_ROOT."css/");
define("LINK_SRC", LINK_ROOT."src/");
define("LINK_WEB", LINK_ROOT."web/");
define("LINK_LOC", LINK_ROOT."local/");
define("LINK_TST", LINK_ROOT."test/");
define("LINK_ADM", LINK_ROOT."admin/");
define("LINK_IMG", LINK_ROOT."img/");

// for display
define("LEGAL_MSG", "The content of these web pages is not generated by and does not represent the views of Santa Clara University or any of its departments or organizations.");
define("TITLE", "A Recipe Website");

// for recipe submission and dynamic serving size
define("UNITS_MASS_METRIC", ['mg', 'milligram[s]?', 'g(ram[s]?)?', 'kg', 'kilogram[s]?']);
define("UNITS_MASS_IMPERIAL", ['oz', 'ounce[s]?', 'lb[s]?', 'pound[s]?']);
define("UNITS_VOL_METRIC", ['ml', 'milliliter[s]?', 'l(iter[s]?)?']);
define("UNITS_VOL_IMPERIAL", ['tsp', 'teaspoon[s]?', 'tbsp', 'tablespoon[s]?', 'fl oz', 'fluid ounce[s]?', 'c(up[s]?)?', 'qt', 'quart[s]?', 'pt', 'pint[s]?', 'gal(lon[s]?)?']);
define("QTY_MATCH", '(?P<quantity>\d+(\.|\/)?\d*)?');
define("UNIT_MATCH", '(?P<unit>('.implode(array_merge(UNITS_MASS_METRIC, UNITS_MASS_IMPERIAL, UNITS_VOL_METRIC, UNITS_VOL_IMPERIAL), "|").')*)?');
define("INGR_MATCH", '(?P<ingredient>\w+((\s|-)?\w)*)');
define("INGR_REGEX", '/^'.QTY_MATCH.'\s?'.UNIT_MATCH.'\s?'.INGR_MATCH.'$/mi');
?>
